---
abstract: 'draw graph as a DSM matrix'
author:
  - 'Joenio Costa <joenio@colivre.coop.br>'
build_requires:
  File::Path: 0
  Graph: 0
  Module::Install::Can: 0
  Test::Class: 0
  Test::File: 0
  Test::Most: 0
  Test::TempDir: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Writer-DSM
requires:
  Chart::Gnuplot: 0
  File::Temp: 0
  Graph::Writer: 0
  List::MoreUtils: 0
  Modern::Perl: 0
  Mojo::Template: 0
  base: 0
version: 0.006
